// Auto-generated: registers ALL WA free components as forge-*
import './animated-image/animated-image.js'; // forge-animated-image
import './animation/animation.js'; // forge-animation
import './avatar/avatar.js'; // forge-avatar
import './badge/badge.js'; // forge-badge
import './breadcrumb/breadcrumb.js'; // forge-breadcrumb
import './breadcrumb-item/breadcrumb-item.js'; // forge-breadcrumb-item
import './button/button.js'; // forge-button
import './button-group/button-group.js'; // forge-button-group
import './callout/callout.js'; // forge-callout
import './card/card.js'; // forge-card
import './carousel/carousel.js'; // forge-carousel
import './carousel-item/carousel-item.js'; // forge-carousel-item
import './checkbox/checkbox.js'; // forge-checkbox
import './color-picker/color-picker.js'; // forge-color-picker
import './comparison/comparison.js'; // forge-comparison
import './copy-button/copy-button.js'; // forge-copy-button
import './details/details.js'; // forge-details
import './dialog/dialog.js'; // forge-dialog
import './divider/divider.js'; // forge-divider
import './drawer/drawer.js'; // forge-drawer
import './dropdown/dropdown.js'; // forge-dropdown
import './dropdown-item/dropdown-item.js'; // forge-dropdown-item
import './format-bytes/format-bytes.js'; // forge-format-bytes
import './format-date/format-date.js'; // forge-format-date
import './format-number/format-number.js'; // forge-format-number
import './icon/icon.js'; // forge-icon
import './include/include.js'; // forge-include
import './input/input.js'; // forge-input
import './intersection-observer/intersection-observer.js'; // forge-intersection-observer
import './mutation-observer/mutation-observer.js'; // forge-mutation-observer
import './number-input/number-input.js'; // forge-number-input
import './option/option.js'; // forge-option
import './popover/popover.js'; // forge-popover
import './popup/popup.js'; // forge-popup
import './progress-bar/progress-bar.js'; // forge-progress-bar
import './progress-ring/progress-ring.js'; // forge-progress-ring
import './qr-code/qr-code.js'; // forge-qr-code
import './radio/radio.js'; // forge-radio
import './radio-group/radio-group.js'; // forge-radio-group
import './rating/rating.js'; // forge-rating
import './relative-time/relative-time.js'; // forge-relative-time
import './resize-observer/resize-observer.js'; // forge-resize-observer
import './scroller/scroller.js'; // forge-scroller
import './select/select.js'; // forge-select
import './skeleton/skeleton.js'; // forge-skeleton
import './slider/slider.js'; // forge-slider
import './spinner/spinner.js'; // forge-spinner
import './split-panel/split-panel.js'; // forge-split-panel
import './switch/switch.js'; // forge-switch
import './tab/tab.js'; // forge-tab
import './tab-group/tab-group.js'; // forge-tab-group
import './tab-panel/tab-panel.js'; // forge-tab-panel
import './tag/tag.js'; // forge-tag
import './textarea/textarea.js'; // forge-textarea
import './tooltip/tooltip.js'; // forge-tooltip
import './tree/tree.js'; // forge-tree
import './tree-item/tree-item.js'; // forge-tree-item
import './zoomable-frame/zoomable-frame.js'; // forge-zoomable-frame
