#!/usr/bin/env node
// Token build step: CSS → SCSS + TS exports
// Reads all theme CSS files, extracts --wa-* tokens, generates dist/tokens/ outputs

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, '..');
const themesDir = resolve(rootDir, 'src/themes');
const outDir = resolve(rootDir, 'dist/tokens');

/** @typedef {{ name: string; value: string }} DesignToken */

/** Extract CSS custom properties from a CSS string */
function extractTokens(css) {
  /** @type {DesignToken[]} */
  const tokens = [];
  const re = /(--[\w-]+)\s*:\s*([^;}]+)/g;
  let match;
  while ((match = re.exec(css)) !== null) {
    tokens.push({ name: match[1].trim(), value: match[2].trim() });
  }
  return tokens;
}

/** Convert token name to camelCase TS const */
function tokenNameToTsConst(name) {
  return name
    .replace(/^--/, '')
    .replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

// Read all theme files
const files = ['shared.css', 'light.css', 'dark.css'];
/** @type {DesignToken[]} */
const allTokens = [];
const seen = new Set();

for (const file of files) {
  const css = readFileSync(resolve(themesDir, file), 'utf-8');
  for (const token of extractTokens(css)) {
    if (!seen.has(token.name)) {
      seen.add(token.name);
      allTokens.push(token);
    }
  }
}

// Generate outputs
mkdirSync(outDir, { recursive: true });

// SCSS variables
const scssLines = allTokens.map((t) => {
  const scssName = t.name.replace(/^--/, '$');
  return `${scssName}: ${t.value};`;
});
const scssContent =
  '// Auto-generated by @adesso-forge/core-ds — do not edit manually\n\n' +
  scssLines.join('\n') +
  '\n';
writeFileSync(resolve(outDir, 'variables.scss'), scssContent);

// TypeScript constants
const tsLines = allTokens.map((t) => {
  const tsName = tokenNameToTsConst(t.name);
  return `export const ${tsName} = ${JSON.stringify(t.value)} as const;`;
});
const tsContent =
  '// Auto-generated by @adesso-forge/core-ds — do not edit manually\n\n' +
  tsLines.join('\n') +
  '\n';
writeFileSync(resolve(outDir, 'tokens.ts'), tsContent);

// JSON for docs/tooling
const jsonContent = JSON.stringify(
  { generated: new Date().toISOString(), tokens: allTokens },
  null,
  2
);
writeFileSync(resolve(outDir, 'tokens.json'), jsonContent + '\n');

console.log(`✓ Generated ${allTokens.length} tokens → dist/tokens/{variables.scss, tokens.ts, tokens.json}`);
